/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.Color;
import javax.swing.JButton;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author henriknilson
 */
public class DetailPanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private IMatDataHandler dataHandler = IMatDataHandler.getInstance();
    private Product product; 
    
    /**
     * Creates new customizer Detail
     */
    public DetailPanel() {
        initComponents();
        
    }
    
    public void update(Product product) {
        this.product = product;
        this.titleLabel.setText(product.getName());
        this.priceLabel.setText(Double.toString(product.getPrice()) + " kr");
        this.imageLabel.setIcon(IMat.dataHandler.getImageIcon(product, 350, 350));
       //this.adjustedPriceLabel.setText(Double.toString(this.product.getPrice()) + " kr");
       this.amountSpinner.setValue(1);
       if(dataHandler.favorites().contains(product)){
           favBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/heart.png")));
        }
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        favBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        amountSpinner = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        addToCartButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(100, 100, 100, 100), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(200, 200, 200))));
        jPanel7.setLayout(new java.awt.GridLayout(2, 2));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        imageLabel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(imageLabel);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        titleLabel.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        titleLabel.setText("title");
        jPanel1.add(titleLabel);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        backButton.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/button.png"))); // NOI18N
        backButton.setText("TILLBAKA");
        backButton.setToolTipText("Sök i butiken");
        backButton.setAlignmentX(0.5F);
        backButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(200, 200, 200)));
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backButton.setFocusPainted(false);
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.setIconTextGap(0);
        backButton.setMargin(null);
        backButton.setMaximumSize(new java.awt.Dimension(75, 60));
        backButton.setMinimumSize(new java.awt.Dimension(75, 40));
        backButton.setPreferredSize(new java.awt.Dimension(75, 40));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel3.add(backButton);

        jPanel1.add(jPanel3);

        priceLabel.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 0, 0));
        priceLabel.setText("price");
        jPanel1.add(priceLabel);

        favBtn.setBackground(new java.awt.Color(255, 255, 255));
        favBtn.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        favBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/heart-open.png"))); // NOI18N
        favBtn.setBorderPainted(false);
        favBtn.setMargin(null);
        favBtn.setMaximumSize(new java.awt.Dimension(60, 60));
        favBtn.setMinimumSize(new java.awt.Dimension(60, 60));
        favBtn.setPreferredSize(new java.awt.Dimension(60, 60));
        favBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/heart.png"))); // NOI18N
        favBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/heart.png"))); // NOI18N
        favBtn.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/heart.png"))); // NOI18N
        favBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/heart.png"))); // NOI18N
        favBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favBtnActionPerformed(evt);
            }
        });
        jPanel1.add(favBtn);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amountSpinner.setMaximumSize(new java.awt.Dimension(30, 30));
        amountSpinner.setMinimumSize(new java.awt.Dimension(30, 30));
        amountSpinner.setPreferredSize(new java.awt.Dimension(100, 30));
        amountSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                amountSpinnerStateChanged(evt);
            }
        });
        jPanel8.add(amountSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 15, -1, -1));

        jPanel1.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addToCartButton.setBackground(new java.awt.Color(255, 153, 153));
        addToCartButton.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        addToCartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/button.png"))); // NOI18N
        addToCartButton.setText("LÄGG TILL");
        addToCartButton.setAlignmentX(0.5F);
        addToCartButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(200, 200, 200)));
        addToCartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addToCartButton.setFocusPainted(false);
        addToCartButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addToCartButton.setIconTextGap(0);
        addToCartButton.setMargin(null);
        addToCartButton.setMaximumSize(new java.awt.Dimension(100, 100));
        addToCartButton.setMinimumSize(new java.awt.Dimension(0, 0));
        addToCartButton.setPreferredSize(new java.awt.Dimension(100, 40));
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });
        jPanel9.add(addToCartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jPanel1.add(jPanel9);

        jPanel2.add(jPanel1);

        jPanel7.add(jPanel2);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac commodo enim, tristique cursus ipsum. Morbi ex augue, dictum id tempor vel, malesuada vel nibh. Nunc cursus purus eget maximus auctor. Vestibulum sagittis pharetra tellus interdum hendrerit. In ultrices mauris egestas pulvinar convallis. Morbi egestas pulvinar elit vitae volutpat. Morbi venenatis tempor ultrices.\n\nEtiam urna lectus, consequat in vestibulum vel, venenatis ac tortor. Donec ut tortor auctor elit luctus varius. Aliquam pulvinar odio nec consequat aliquet. Praesent tempus orci justo, molestie convallis lacus faucibus sit amet. Curabitur vel ante sodales, lobortis arcu vel, fermentum turpis. Cras imperdiet, ex nec fermentum congue, justo metus iaculis lectus, vel aliquet risus enim ut leo. Maecenas hendrerit ut nunc id pharetra. Curabitur sed magna sapien. Ut luctus, turpis id fermentum mattis, arcu velit blandit diam, vel consectetur lorem odio elementum felis. Donec orci ipsum, dictum ac ligula sed, ullamcorper commodo neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel7.add(jScrollPane1);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void favBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favBtnActionPerformed
        if(dataHandler.favorites().contains(product)){
            dataHandler.favorites().remove(product);
            favBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/heart-open.png")));
        }else{
            dataHandler.addFavorite(product);
            favBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imat/resources/heart.png")));
        }
    }//GEN-LAST:event_favBtnActionPerformed

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        boolean exists = false;

        for(int i = 0; i < dataHandler.getShoppingCart().getItems().size(); i++){
            ShoppingItem temp = dataHandler.getShoppingCart().getItems().get(i);
            if(temp.getProduct() == product){
                temp.setAmount(temp.getAmount() + (Integer)amountSpinner.getValue());
                dataHandler.getShoppingCart().fireShoppingCartChanged(temp, true);
                exists = true;
                break;
            }
        }

        if(!exists){
            dataHandler.getShoppingCart().addProduct(product, (Integer)amountSpinner.getValue());
        }
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void amountSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_amountSpinnerStateChanged
        if((Integer)amountSpinner.getValue() < 1)
            amountSpinner.setValue(1);
        this.priceLabel.setText(Double.toString(((Integer)amountSpinner.getValue()) * this.product.getPrice()) + " kr");
    }//GEN-LAST:event_amountSpinnerStateChanged

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JButton backButton;
    private javax.swing.JButton favBtn;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
