/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.AbstractButton;

/**
 *
 * @author kakan
 */
public class HintsPanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private final int NUMBER_OF_HINTS = 37;
    private int currentHintNbr;

    /**
     * Creates new customizer HintsPanel
     */
    public HintsPanel() {
        initComponents();
        currentHintNbr = 13;
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    
    private void changeToHint(int changeNumber) {
        if (1 <= changeNumber && changeNumber <= NUMBER_OF_HINTS) {
            hintsHeaderLabel.setText("Tips " + changeNumber + "/" + NUMBER_OF_HINTS);
            currentHintTextField.setText(String.valueOf(changeNumber));
            
            if (2 < changeNumber) {
                minusOneButton.setText(String.valueOf(changeNumber-1));
                minusTwoButton.setText(String.valueOf(changeNumber-2));
            } else {
                 minusOneButton.setText(String.valueOf(2));
                 minusTwoButton.setText(String.valueOf(1));
            }
            
            if(changeNumber < NUMBER_OF_HINTS) {
                plusOneButton.setText(String.valueOf(changeNumber+1));
                plusTwoButton.setText(String.valueOf(changeNumber+2));
            } else {
                plusOneButton.setText(String.valueOf(NUMBER_OF_HINTS-1));
                plusTwoButton.setText(String.valueOf(NUMBER_OF_HINTS));
            }
            if (currentHintNbr != changeNumber) {
                currentHintNbr = changeNumber;
                String dummyText = "";
                boolean startOfSentence = false;
                Random r = new Random();
                for (int i = 0; i < 5000; i++) {
                    if (i%20 == 19 && r.nextInt(3) == 0 && !startOfSentence) {
                        dummyText += ". ";
                        startOfSentence = true;
                    } else if (i%7 == 6 && r.nextInt(2) == 0 && !startOfSentence) {
                        dummyText += " ";
                    }
                    else {
                        if (startOfSentence) {
                            dummyText += String.valueOf((char)(r.nextInt((122 - 97) + 1) + 97)).toUpperCase();
                            startOfSentence = false;
                        } else {
                            dummyText += String.valueOf((char)(r.nextInt((122 - 97) + 1) + 97)).toLowerCase();
                        }
                    }
                }
                currentHintTextArea.setText(dummyText);
            }
            
        }
        
    }
    
    private void changeCurrentHintToButtonText(AbstractButton button) {
        changeToHint(Integer.parseInt(button.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hintsButtonGroup = new javax.swing.ButtonGroup();
        currentTipsLayoutPanel = new javax.swing.JPanel();
        currentTipsPanel = new javax.swing.JPanel();
        hintsHeaderLabel = new javax.swing.JLabel();
        needHelpPanel = new javax.swing.JPanel();
        needHelpLabel = new javax.swing.JLabel();
        findHelpPanel = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        currentHintScrollPane = new javax.swing.JScrollPane();
        currentHintTextArea = new javax.swing.JTextArea();
        hintsNavigationPanel = new javax.swing.JPanel();
        previousButton = new javax.swing.JButton();
        firstButton = new javax.swing.JButton();
        secondButton = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        minusTwoButton = new javax.swing.JButton();
        minusOneButton = new javax.swing.JButton();
        currentHintTextField = new javax.swing.JTextField();
        plusOneButton = new javax.swing.JButton();
        plusTwoButton = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        secondLastButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        manualPanel = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        hintsHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintsHeaderLabel.setText("Tips 13/37");

        needHelpPanel.setBorder(null);
        needHelpPanel.setLayout(new java.awt.BorderLayout());

        needHelpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        needHelpLabel.setText("Behöver du hjälp?");
        needHelpPanel.add(needHelpLabel, java.awt.BorderLayout.NORTH);

        jLabel65.setText("Besök vårt");
        findHelpPanel.add(jLabel65);

        jButton33.setText("forum");
        findHelpPanel.add(jButton33);

        jLabel66.setText("eller");
        findHelpPanel.add(jLabel66);

        jButton34.setText("kontakta oss");
        findHelpPanel.add(jButton34);

        needHelpPanel.add(findHelpPanel, java.awt.BorderLayout.CENTER);

        currentHintScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        currentHintTextArea.setColumns(20);
        currentHintTextArea.setLineWrap(true);
        currentHintTextArea.setRows(5);
        currentHintTextArea.setText("Lorem ipsum dolor sit amet, consectetur adipisicing elit,\nsed do eiusmod tempor incididunt ut labore et dolore\n magna aliqua. Ut enim ad minim veniam, quis \nnostrud exercitation ullamco \n\nlaboris nisi ut aliquip ex ea commodo consequat\n. Duis aute irure dolor in reprehenderit in voluptate velit \nesse cillum dolore eu fugiat nulla pariatur. \n\nExcepteur sint occaecat cupidatat non proident, sunt \nin culpa qui officia deserunt mollit anim id est laborum.\n");
        currentHintTextArea.setWrapStyleWord(true);
        currentHintTextArea.setAutoscrolls(false);
        currentHintScrollPane.setViewportView(currentHintTextArea);

        previousButton.setText("<<");
        hintsButtonGroup.add(previousButton);
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(previousButton);

        firstButton.setText("1");
        hintsButtonGroup.add(firstButton);
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(firstButton);

        secondButton.setText("2");
        hintsButtonGroup.add(secondButton);
        secondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondButtonActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(secondButton);

        jLabel63.setText(". . .");
        hintsNavigationPanel.add(jLabel63);

        minusTwoButton.setText("11");
        minusTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusTwoButtonActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(minusTwoButton);

        minusOneButton.setText("12");
        hintsButtonGroup.add(minusOneButton);
        minusOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusOneButtonActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(minusOneButton);

        currentHintTextField.setText("13");
        currentHintTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentHintTextFieldActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(currentHintTextField);

        plusOneButton.setText("14");
        hintsButtonGroup.add(plusOneButton);
        plusOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusOneButtonActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(plusOneButton);

        plusTwoButton.setText("15");
        plusTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusTwoButtonActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(plusTwoButton);

        jLabel62.setText(". . .");
        hintsNavigationPanel.add(jLabel62);

        secondLastButton.setText("36");
        hintsButtonGroup.add(secondLastButton);
        secondLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondLastButtonActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(secondLastButton);

        lastButton.setText("37");
        hintsButtonGroup.add(lastButton);
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(lastButton);

        nextButton.setText(">>");
        hintsButtonGroup.add(nextButton);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        hintsNavigationPanel.add(nextButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hintsNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(currentHintScrollPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentHintScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hintsNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout currentTipsPanelLayout = new javax.swing.GroupLayout(currentTipsPanel);
        currentTipsPanel.setLayout(currentTipsPanelLayout);
        currentTipsPanelLayout.setHorizontalGroup(
            currentTipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTipsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(currentTipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(needHelpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hintsHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        currentTipsPanelLayout.setVerticalGroup(
            currentTipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTipsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hintsHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(needHelpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 632, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout currentTipsLayoutPanelLayout = new javax.swing.GroupLayout(currentTipsLayoutPanel);
        currentTipsLayoutPanel.setLayout(currentTipsLayoutPanelLayout);
        currentTipsLayoutPanelLayout.setHorizontalGroup(
            currentTipsLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTipsLayoutPanelLayout.createSequentialGroup()
                .addComponent(currentTipsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        currentTipsLayoutPanelLayout.setVerticalGroup(
            currentTipsLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentTipsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(currentTipsLayoutPanel);

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Manual");

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor sit amet, consectetur adipisicing elit,\nsed do eiusmod tempor incididunt ut labore et dolore\n magna aliqua. Ut enim ad minim veniam, quis \nnostrud exercitation ullamco \n\nlaboris nisi ut aliquip ex ea commodo consequat\n. Duis aute irure dolor in reprehenderit in voluptate velit \nesse cillum dolore eu fugiat nulla pariatur. \n\nExcepteur sint occaecat cupidatat non proident, sunt \nin culpa qui officia deserunt mollit anim id est laborum.\n");
        jTextArea1.setToolTipText("");
        jScrollPane6.setViewportView(jTextArea1);

        javax.swing.GroupLayout manualPanelLayout = new javax.swing.GroupLayout(manualPanel);
        manualPanel.setLayout(manualPanelLayout);
        manualPanelLayout.setHorizontalGroup(
            manualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manualPanelLayout.createSequentialGroup()
                .addGroup(manualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                .addContainerGap())
        );
        manualPanelLayout.setVerticalGroup(
            manualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manualPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(manualPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void currentHintTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentHintTextFieldActionPerformed
        Pattern ALLOWED_HINT_NUMBER = Pattern.compile("^\\d{0,2}$");
        Matcher m = ALLOWED_HINT_NUMBER.matcher(currentHintTextField.getText());
        if (m.find()) {
            int showHintNbr;
            if (currentHintTextField.getText().equals("")) {
                showHintNbr = 1;
            } else {
                showHintNbr = Integer.parseInt(currentHintTextField.getText());
            }
            if (showHintNbr < NUMBER_OF_HINTS) {
                changeToHint(showHintNbr);
            } else {
                currentHintTextField.setText(String.valueOf(currentHintNbr));
            }
        } else {
            currentHintTextField.setText(String.valueOf(currentHintNbr));
        }
    }//GEN-LAST:event_currentHintTextFieldActionPerformed
    
    private void minusOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusOneButtonActionPerformed
        changeCurrentHintToButtonText((AbstractButton)evt.getSource());
    }//GEN-LAST:event_minusOneButtonActionPerformed

    private void plusOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusOneButtonActionPerformed
        changeCurrentHintToButtonText((AbstractButton)evt.getSource());
    }//GEN-LAST:event_plusOneButtonActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        changeCurrentHintToButtonText((AbstractButton)evt.getSource());
    }//GEN-LAST:event_firstButtonActionPerformed

    private void secondButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondButtonActionPerformed
        changeCurrentHintToButtonText((AbstractButton)evt.getSource());
    }//GEN-LAST:event_secondButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        changeCurrentHintToButtonText((AbstractButton)evt.getSource());
    }//GEN-LAST:event_lastButtonActionPerformed

    private void secondLastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondLastButtonActionPerformed
        changeCurrentHintToButtonText((AbstractButton)evt.getSource());
    }//GEN-LAST:event_secondLastButtonActionPerformed

    private void minusTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusTwoButtonActionPerformed
        changeCurrentHintToButtonText((AbstractButton)evt.getSource());
    }//GEN-LAST:event_minusTwoButtonActionPerformed

    private void plusTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusTwoButtonActionPerformed
        changeCurrentHintToButtonText((AbstractButton)evt.getSource());
    }//GEN-LAST:event_plusTwoButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        changeToHint(currentHintNbr-1);
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        changeToHint(currentHintNbr+1);
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane currentHintScrollPane;
    private javax.swing.JTextArea currentHintTextArea;
    private javax.swing.JTextField currentHintTextField;
    private javax.swing.JPanel currentTipsLayoutPanel;
    private javax.swing.JPanel currentTipsPanel;
    private javax.swing.JPanel findHelpPanel;
    private javax.swing.JButton firstButton;
    private javax.swing.ButtonGroup hintsButtonGroup;
    private javax.swing.JLabel hintsHeaderLabel;
    private javax.swing.JPanel hintsNavigationPanel;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton lastButton;
    private javax.swing.JPanel manualPanel;
    private javax.swing.JButton minusOneButton;
    private javax.swing.JButton minusTwoButton;
    private javax.swing.JLabel needHelpLabel;
    private javax.swing.JPanel needHelpPanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton plusOneButton;
    private javax.swing.JButton plusTwoButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton secondButton;
    private javax.swing.JButton secondLastButton;
    // End of variables declaration//GEN-END:variables


}