/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;

/**
 *
 * @author kakan
 */
public class MyPreferenses extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private DefaultListModel favourites = new DefaultListModel();
    private DefaultListModel ignores = new DefaultListModel();
    private IMatDataHandler idh = IMatDataHandler.getInstance();

    /**
     * Creates new customizer MyPreferenses
     */
    public MyPreferenses() {
        initComponents();
        
        myFavoritesLabel.setText("<html><h2>Mina favoriter</h2></html>");
        myIgnoresLabel.setText("<html><h2>Mina borttagna varor</h2></html>");
        clearInfoLabel.setText("<html><h2>Ta bort personlig information</h2></html>");
        
        if (idh.favorites().size() == 0) {
            favourites.addElement("Du har inga favoriter.");
        } else {
            for(Product p : idh.favorites()){
                favourites.addElement(p.getName());           
            }
        }
        myFavouritesList.setModel(favourites);

        ignores.addElement("Du har inga borttagna varor.");
        myIgnoresList.setModel(ignores);
        
    }

    MyPreferenses(int width, int height) {
        this();
        super.setSize(width, height);
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    
    public void removeALLInformation() {
        int result = JOptionPane.showConfirmDialog(null, "Är du säker på att du vill ta bort ALL sparad information?", "Bekräftelse", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            idh.reset();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPreferenses = new javax.swing.JPanel();
        myFavouritesPanel = new javax.swing.JPanel();
        myFavoritesLabel = new javax.swing.JLabel();
        myFavouritesScrollPane = new javax.swing.JScrollPane();
        myFavouritesList = new javax.swing.JList();
        myIgnoresLabel = new javax.swing.JLabel();
        myIgnoresScrollPane = new javax.swing.JScrollPane();
        myIgnoresList = new javax.swing.JList();
        clearInfoPanel = new javax.swing.JPanel();
        clearInfoLabel = new javax.swing.JLabel();
        deleteCardInfoButton = new javax.swing.JButton();
        deleteAllInfoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(200, 200, 200)), javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)));
        setLayout(new java.awt.GridLayout(2, 1));

        myPreferenses.setBackground(new java.awt.Color(255, 255, 255));
        myPreferenses.setPreferredSize(new java.awt.Dimension(301, 505));
        myPreferenses.setLayout(new java.awt.GridLayout(1, 0));

        myFavouritesPanel.setBackground(new java.awt.Color(255, 255, 255));

        myFavoritesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myFavoritesLabel.setText("Mina favoriter");

        myFavouritesScrollPane.setViewportView(myFavouritesList);

        myIgnoresLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myIgnoresLabel.setText("Mina borttagna varor");

        myIgnoresScrollPane.setViewportView(myIgnoresList);

        javax.swing.GroupLayout myFavouritesPanelLayout = new javax.swing.GroupLayout(myFavouritesPanel);
        myFavouritesPanel.setLayout(myFavouritesPanelLayout);
        myFavouritesPanelLayout.setHorizontalGroup(
            myFavouritesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myFavouritesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myFavouritesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myIgnoresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myFavouritesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(myFavoritesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myIgnoresScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        myFavouritesPanelLayout.setVerticalGroup(
            myFavouritesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myFavouritesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myFavoritesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myFavouritesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myIgnoresLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myIgnoresScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        myPreferenses.add(myFavouritesPanel);

        add(myPreferenses);

        clearInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        clearInfoLabel.setText("Ta bort personlig information");

        deleteCardInfoButton.setText("Genomför");
        deleteCardInfoButton.setToolTipText("Tar bort ALL personlig information ");
        deleteCardInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCardInfoButtonActionPerformed(evt);
            }
        });

        deleteAllInfoButton.setText("Genomför");
        deleteAllInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllInfoButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Rensa allt:");

        jLabel2.setText("Rensa kortuppgifter");

        javax.swing.GroupLayout clearInfoPanelLayout = new javax.swing.GroupLayout(clearInfoPanel);
        clearInfoPanel.setLayout(clearInfoPanelLayout);
        clearInfoPanelLayout.setHorizontalGroup(
            clearInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clearInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearInfoLabel)
                    .addGroup(clearInfoPanelLayout.createSequentialGroup()
                        .addGroup(clearInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clearInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteCardInfoButton)
                            .addComponent(deleteAllInfoButton))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        clearInfoPanelLayout.setVerticalGroup(
            clearInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clearInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCardInfoButton)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clearInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteAllInfoButton)
                    .addComponent(jLabel1))
                .addContainerGap(392, Short.MAX_VALUE))
        );

        add(clearInfoPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteCardInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCardInfoButtonActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Är du säker på att du vill ta bort sparad kortuppgifter?", "Bekräftelse", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            idh.getCreditCard().setCardNumber(null);
            idh.getCreditCard().setCardType(null);
            idh.getCreditCard().setHoldersName(null);
            idh.getCreditCard().setValidMonth(0);
            idh.getCreditCard().setValidYear(0);
            idh.getCreditCard().setVerificationCode(0);
        }
    }//GEN-LAST:event_deleteCardInfoButtonActionPerformed

    private void deleteAllInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllInfoButtonActionPerformed
        removeALLInformation();
    }//GEN-LAST:event_deleteAllInfoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clearInfoLabel;
    private javax.swing.JPanel clearInfoPanel;
    private javax.swing.JButton deleteAllInfoButton;
    private javax.swing.JButton deleteCardInfoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel myFavoritesLabel;
    private javax.swing.JList myFavouritesList;
    private javax.swing.JPanel myFavouritesPanel;
    private javax.swing.JScrollPane myFavouritesScrollPane;
    private javax.swing.JLabel myIgnoresLabel;
    private javax.swing.JList myIgnoresList;
    private javax.swing.JScrollPane myIgnoresScrollPane;
    private javax.swing.JPanel myPreferenses;
    // End of variables declaration//GEN-END:variables
}
