/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.util.List;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ProductCategory;

/**
 *
 * @author filip
 */
public class ProductCategoryPanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer PageCard
     */
    public ProductCategoryPanel() {
        initComponents();
    }
    
    public ProductCategoryPanel(ProductCategory... productCategories) {
        this();
        this.addProducts(productCategories);
    }
    
    public ProductCategoryPanel(List<Product> products) {
        this();
        for(Product product : products) {
                
            ProductPanel productPanel = new ProductPanel(product);
            productPanel.setSize(200, 100);
            productsPanel.add(productPanel);
        }
    }
    
    private void addProducts(ProductCategory[] productCategories) {
        for(ProductCategory productCategory : productCategories) {
            List<Product> products = IMat.dataHandler.getProducts(productCategory);
            for(Product product : products) {
                
                ProductPanel productPanel = new ProductPanel(product);
                productPanel.setSize(200, 100);
                productsPanel.add(productPanel);
            }
        }
    }
    
    public void applyFilters(FilterPanel filterCard) {
        productsPanel.removeAll();
        filterPanel.removeAll();
        filterPanel.add(filterCard);
        for(Product product : filterCard.getSelected()) {
            
            ProductPanel productPanel = new ProductPanel(product);
            productPanel.setSize(200, 100);
            productsPanel.add(productPanel);

        }
        this.revalidate();
        this.repaint();
    }
    
    public void applySearchResult(List<Product> products) {
        productsPanel.removeAll();
        filterPanel.removeAll();
        
        for(Product product : products) {
            
            ProductPanel productPanel = new ProductPanel(product);
            productPanel.setSize(200, 100);
            productsPanel.add(productPanel);

        }
        this.revalidate();
        this.repaint();
    }
    
    
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterPanel = new javax.swing.JPanel();
        productsScrollPane = new javax.swing.JScrollPane();
        productsPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(100, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        filterPanel.setBackground(new java.awt.Color(255, 255, 255));
        filterPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(200, 200, 200)), javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)));
        filterPanel.setMaximumSize(new java.awt.Dimension(230, 2147483647));
        filterPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        filterPanel.setPreferredSize(new java.awt.Dimension(230, 0));
        filterPanel.setLayout(new java.awt.BorderLayout());
        add(filterPanel);

        productsScrollPane.setBorder(null);
        productsScrollPane.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        productsScrollPane.setMinimumSize(new java.awt.Dimension(0, 0));

        productsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        productsPanel.setMaximumSize(new java.awt.Dimension(1084, 2147483647));
        productsPanel.setMinimumSize(new java.awt.Dimension(1084, 2147483647));
        productsPanel.setLayout(new java.awt.GridLayout(0, 3, 20, 20));
        productsScrollPane.setViewportView(productsPanel);

        add(productsScrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JScrollPane productsScrollPane;
    // End of variables declaration//GEN-END:variables
}
