/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.GridLayout;
import java.util.List;
import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author filip
 */
public class ProductListPanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private IMatDataHandler dataHandler = IMatDataHandler.getInstance();
    private ShoppingCart cart = dataHandler.getShoppingCart();

    /**
     * Creates new customizer PageCard
     */
    public ProductListPanel() {
        initComponents();
        updatePanel();
    }

    
    private void addProducts(ShoppingCart cart) {
        
        productsPanel.removeAll();
        
        for(ShoppingItem item : cart.getItems()){

            ListedProductPanel listedProductPanel = new ListedProductPanel(item);
            productsPanel.add(listedProductPanel);
        }

    }
    
    public void updatePanel(){
        
        if(cart.getItems().size() >= 6){
            ((GridLayout)productsPanel.getLayout()).setRows(cart.getItems().size());
        }else{
            ((GridLayout)productsPanel.getLayout()).setRows(6);
        }
        this.addProducts(cart);
    }
    
    
    
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productsScrollPane = new javax.swing.JScrollPane();
        productsPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(100, 200));

        productsScrollPane.setBorder(null);
        productsScrollPane.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        productsScrollPane.setMinimumSize(new java.awt.Dimension(0, 0));

        productsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        productsPanel.setMaximumSize(new java.awt.Dimension(1084, 2147483647));
        productsPanel.setMinimumSize(new java.awt.Dimension(1084, 2147483647));
        productsPanel.setLayout(new java.awt.GridLayout(1, 1, 20, 20));
        productsScrollPane.setViewportView(productsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel productsPanel;
    private javax.swing.JScrollPane productsScrollPane;
    // End of variables declaration//GEN-END:variables
}
