/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.BorderLayout;
import javax.swing.BoxLayout;

/**
 *
 * @author kakan
 */
public class ProfilePanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private static ReminderAndStoredInformation r;

    /**
     * Creates new customizer ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
        
        this.add(new ReminderAndStoredInformation());
        this.add(new MyPreviousShopping());
        this.add(new MyPreferenses());
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    
    public static ReminderAndStoredInformation getReminderAndStoredInformation() {
        return r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setLayout(new java.awt.GridLayout(1, 3, 20, 0));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
