/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.BorderLayout;
import javax.swing.BoxLayout;

/**
 *
 * @author kakan
 */
public class ProfilePanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
        this.add(new ReminderAndStoredInformation(this.getWidth()/3, this.getHeight()));
        this.add(new MyPreviousShopping(this.getWidth()/3, this.getHeight()));
        this.add(new MyPreferenses(this.getWidth()/3, this.getHeight()));
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
