/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import javax.swing.DefaultListModel;

/**
 *
 * @author kakan
 */
public class RecipePanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private DefaultListModel updateListModel;

    /**
     * Creates new customizer recipePanel
     */
    public RecipePanel() {
        initComponents();
        updateListModel = new DefaultListModel();
        recipeSelectList.setModel(updateListModel);
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recipePanel = new javax.swing.JPanel();
        recipeResultPanel = new javax.swing.JPanel();
        recipeSearchAndSelectPanel = new javax.swing.JPanel();
        receipeSearchPanel = new javax.swing.JPanel();
        receipeSearchTitle = new javax.swing.JLabel();
        recipeSearchWord = new javax.swing.JLabel();
        recipeSearchWordTextField = new javax.swing.JTextField();
        recipeSearchMaxPrice = new javax.swing.JLabel();
        recipeSearchMaxPriceTextField = new javax.swing.JTextField();
        recipeSearchMaxTime = new javax.swing.JLabel();
        recipeSearchMaxTimeSlider = new javax.swing.JSlider();
        searchButton = new javax.swing.JButton();
        recipeSelectScrollPane = new javax.swing.JScrollPane();
        recipeSelectList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        recipePanel.setLayout(new java.awt.BorderLayout());

        recipeResultPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout recipeResultPanelLayout = new javax.swing.GroupLayout(recipeResultPanel);
        recipeResultPanel.setLayout(recipeResultPanelLayout);
        recipeResultPanelLayout.setHorizontalGroup(
            recipeResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        recipeResultPanelLayout.setVerticalGroup(
            recipeResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        recipePanel.add(recipeResultPanel, java.awt.BorderLayout.CENTER);

        recipeSearchAndSelectPanel.setPreferredSize(new java.awt.Dimension(400, 100));
        recipeSearchAndSelectPanel.setLayout(new java.awt.GridLayout(2, 0));

        receipeSearchPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        receipeSearchTitle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        receipeSearchTitle.setText("Sök recept");

        recipeSearchWord.setText("Sökord");

        recipeSearchMaxPrice.setText("Max pris (kr)");

        recipeSearchMaxTime.setText("Tillagningstid");
        recipeSearchMaxTime.setToolTipText("Välj maximal tillagningstid");

        recipeSearchMaxTimeSlider.setMajorTickSpacing(30);
        recipeSearchMaxTimeSlider.setMaximum(180);
        recipeSearchMaxTimeSlider.setPaintLabels(true);
        recipeSearchMaxTimeSlider.setPaintTicks(true);
        recipeSearchMaxTimeSlider.setToolTipText("");
        recipeSearchMaxTimeSlider.setValue(90);

        searchButton.setText("Sök!");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout receipeSearchPanelLayout = new javax.swing.GroupLayout(receipeSearchPanel);
        receipeSearchPanel.setLayout(receipeSearchPanelLayout);
        receipeSearchPanelLayout.setHorizontalGroup(
            receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                                .addComponent(recipeSearchMaxTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recipeSearchMaxTimeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                            .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(recipeSearchMaxPrice)
                                    .addComponent(recipeSearchWord))
                                .addGap(24, 24, 24)
                                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recipeSearchWordTextField)
                                    .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                                        .addComponent(recipeSearchMaxPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                        .addComponent(receipeSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receipeSearchPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        receipeSearchPanelLayout.setVerticalGroup(
            receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receipeSearchTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipeSearchWord)
                    .addComponent(recipeSearchWordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipeSearchMaxPrice)
                    .addComponent(recipeSearchMaxPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(recipeSearchMaxTime))
                    .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recipeSearchMaxTimeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addContainerGap())
        );

        recipeSearchAndSelectPanel.add(receipeSearchPanel);

        recipeSelectScrollPane.setViewportView(recipeSelectList);

        recipeSearchAndSelectPanel.add(recipeSelectScrollPane);

        recipePanel.add(recipeSearchAndSelectPanel, java.awt.BorderLayout.WEST);

        add(recipePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        updateListModel.removeAllElements();
        updateListModel.addElement("Inget recept matchar sökningen.");
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel receipeSearchPanel;
    private javax.swing.JLabel receipeSearchTitle;
    private javax.swing.JPanel recipePanel;
    private javax.swing.JPanel recipeResultPanel;
    private javax.swing.JPanel recipeSearchAndSelectPanel;
    private javax.swing.JLabel recipeSearchMaxPrice;
    private javax.swing.JTextField recipeSearchMaxPriceTextField;
    private javax.swing.JLabel recipeSearchMaxTime;
    private javax.swing.JSlider recipeSearchMaxTimeSlider;
    private javax.swing.JLabel recipeSearchWord;
    private javax.swing.JTextField recipeSearchWordTextField;
    private javax.swing.JList recipeSelectList;
    private javax.swing.JScrollPane recipeSelectScrollPane;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
