/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import javax.swing.DefaultListModel;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author kakan
 */
public class RecipePanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private DefaultListModel updateListModel;
    IMatDataHandler dataHandler = IMatDataHandler.getInstance();

    /**
     * Creates new customizer recipePanel
     */
    public RecipePanel() {
        initComponents();
        updateListModel = new DefaultListModel();
        recipeSelectList.setModel(updateListModel);
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recipePanel = new javax.swing.JPanel();
        recipeResultPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        recipePortionsSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        recipeSearchAndSelectPanel = new javax.swing.JPanel();
        receipeSearchPanel = new javax.swing.JPanel();
        receipeSearchTitle = new javax.swing.JLabel();
        recipeSearchWord = new javax.swing.JLabel();
        recipeSearchWordTextField = new javax.swing.JTextField();
        recipeSearchMaxPrice = new javax.swing.JLabel();
        recipeSearchMaxPriceTextField = new javax.swing.JTextField();
        recipeSearchMaxTime = new javax.swing.JLabel();
        recipeSearchMaxTimeSlider = new javax.swing.JSlider();
        searchButton = new javax.swing.JButton();
        recipeSelectScrollPane = new javax.swing.JScrollPane();
        recipeSelectList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        recipePanel.setLayout(new java.awt.BorderLayout());

        recipeResultPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Ninjabiffar med ris");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("4  kg Köttfärs nöt");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("4 kg Jasmin-risi");

        recipePortionsSlider.setMajorTickSpacing(1);
        recipePortionsSlider.setMaximum(8);
        recipePortionsSlider.setMinimum(1);
        recipePortionsSlider.setPaintLabels(true);
        recipePortionsSlider.setPaintTicks(true);
        recipePortionsSlider.setToolTipText("");
        recipePortionsSlider.setValue(4);
        recipePortionsSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                recipePortionsSliderStateChanged(evt);
            }
        });

        jLabel2.setText("Portioner:");

        jButton1.setText("Lägg till i varukorg");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(recipePortionsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recipePortionsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout recipeResultPanelLayout = new javax.swing.GroupLayout(recipeResultPanel);
        recipeResultPanel.setLayout(recipeResultPanelLayout);
        recipeResultPanelLayout.setHorizontalGroup(
            recipeResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        recipeResultPanelLayout.setVerticalGroup(
            recipeResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipeResultPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        recipePanel.add(recipeResultPanel, java.awt.BorderLayout.CENTER);

        recipeSearchAndSelectPanel.setPreferredSize(new java.awt.Dimension(400, 100));
        recipeSearchAndSelectPanel.setLayout(new java.awt.GridLayout(2, 0));

        receipeSearchPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        receipeSearchTitle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        receipeSearchTitle.setText("Sök recept");

        recipeSearchWord.setText("Sökord");

        recipeSearchMaxPrice.setText("Max pris (kr)");

        recipeSearchMaxTime.setText("Tillagningstid");
        recipeSearchMaxTime.setToolTipText("Välj maximal tillagningstid");

        recipeSearchMaxTimeSlider.setMajorTickSpacing(30);
        recipeSearchMaxTimeSlider.setMaximum(180);
        recipeSearchMaxTimeSlider.setPaintLabels(true);
        recipeSearchMaxTimeSlider.setPaintTicks(true);
        recipeSearchMaxTimeSlider.setToolTipText("");
        recipeSearchMaxTimeSlider.setValue(90);

        searchButton.setText("Sök!");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout receipeSearchPanelLayout = new javax.swing.GroupLayout(receipeSearchPanel);
        receipeSearchPanel.setLayout(receipeSearchPanelLayout);
        receipeSearchPanelLayout.setHorizontalGroup(
            receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                                .addComponent(recipeSearchMaxTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recipeSearchMaxTimeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                            .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(recipeSearchMaxPrice)
                                    .addComponent(recipeSearchWord))
                                .addGap(24, 24, 24)
                                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recipeSearchWordTextField)
                                    .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                                        .addComponent(recipeSearchMaxPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                        .addComponent(receipeSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receipeSearchPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        receipeSearchPanelLayout.setVerticalGroup(
            receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receipeSearchTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipeSearchWord)
                    .addComponent(recipeSearchWordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipeSearchMaxPrice)
                    .addComponent(recipeSearchMaxPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(receipeSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(recipeSearchMaxTime))
                    .addGroup(receipeSearchPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recipeSearchMaxTimeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addContainerGap())
        );

        recipeSearchAndSelectPanel.add(receipeSearchPanel);

        recipeSelectScrollPane.setViewportView(recipeSelectList);

        recipeSearchAndSelectPanel.add(recipeSelectScrollPane);

        recipePanel.add(recipeSearchAndSelectPanel, java.awt.BorderLayout.WEST);

        add(recipePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        updateListModel.removeAllElements();
        updateListModel.addElement("Inget recept matchar sökningen.");
    }//GEN-LAST:event_searchButtonActionPerformed

    private void recipePortionsSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_recipePortionsSliderStateChanged
        jCheckBox1.setText(recipePortionsSlider.getValue() + " kg Köttfärs nöt");
        jCheckBox2.setText(recipePortionsSlider.getValue() + " kg Jasmin-ris");
    }//GEN-LAST:event_recipePortionsSliderStateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jCheckBox1.isSelected()){
            //dataHandler.getShoppingCart().addProduct(dataHandler.findProducts("Köttfärs nöt").get(0), recipePortionsSlider.getValue());
            Product product = dataHandler.findProducts("Köttfärs nöt").get(0);
            
            boolean exists = false;
                
            for(int i = 0; i < dataHandler.getShoppingCart().getItems().size(); i++){
                ShoppingItem temp = dataHandler.getShoppingCart().getItems().get(i);
                if(temp.getProduct() == product){
                    temp.setAmount(temp.getAmount() + recipePortionsSlider.getValue());
                    dataHandler.getShoppingCart().fireShoppingCartChanged(temp, true);
                    exists = true;
                    break;
                }
            }
            
            if(!exists){
                dataHandler.getShoppingCart().addProduct(product, recipePortionsSlider.getValue());
            }
        }
        
        if(jCheckBox2.isSelected()){
            //dataHandler.getShoppingCart().addProduct(dataHandler.findProducts("Spaghetti").get(0), recipePortionsSlider.getValue());
            
            Product product = dataHandler.findProducts("Jasmin-ris").get(0);
            
            boolean exists = false;
                
            for(int i = 0; i < dataHandler.getShoppingCart().getItems().size(); i++){
                ShoppingItem temp = dataHandler.getShoppingCart().getItems().get(i);
                if(temp.getProduct() == product){
                    temp.setAmount(temp.getAmount() + recipePortionsSlider.getValue());
                    dataHandler.getShoppingCart().fireShoppingCartChanged(temp, true);
                    exists = true;
                    break;
                }
            }
            
            if(!exists){
                dataHandler.getShoppingCart().addProduct(product, recipePortionsSlider.getValue());
            }
        }
        
        
        
        ((IMat)this.getTopLevelAncestor()).getLayeredPane().moveToFront(((IMat)this.getTopLevelAncestor()).getCardPanel());
        ((IMat)this.getTopLevelAncestor()).getLayeredPane().moveToBack(((IMat)this.getTopLevelAncestor()).getCartPanel());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel receipeSearchPanel;
    private javax.swing.JLabel receipeSearchTitle;
    private javax.swing.JPanel recipePanel;
    private javax.swing.JSlider recipePortionsSlider;
    private javax.swing.JPanel recipeResultPanel;
    private javax.swing.JPanel recipeSearchAndSelectPanel;
    private javax.swing.JLabel recipeSearchMaxPrice;
    private javax.swing.JTextField recipeSearchMaxPriceTextField;
    private javax.swing.JLabel recipeSearchMaxTime;
    private javax.swing.JSlider recipeSearchMaxTimeSlider;
    private javax.swing.JLabel recipeSearchWord;
    private javax.swing.JTextField recipeSearchWordTextField;
    private javax.swing.JList recipeSelectList;
    private javax.swing.JScrollPane recipeSelectScrollPane;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
