/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import se.chalmers.ait.dat215.project.IMatDataHandler;

/**
 *
 * @author kakan
 */
public class WelcomePanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer welcomePanel
     */
    public WelcomePanel() {
        initComponents();
        welcomeLabel.setText("<html>  <h1> Välkommen " + IMatDataHandler.getInstance().getCustomer().getFirstName() /*Alexandra!*/ + " </h1> </html>");
        recipeLabel.setText("<html> <h2> Dagens recept:   " + getRecipeOfTheDay() + "</h2> </html>");
        
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    
    public String getRecipeOfTheDay() {
        //Unimplemented
        return "Ninjabiffar med ris";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        navigationPanel = new javax.swing.JPanel();
        newsPanel = new javax.swing.JPanel();
        recipePanel = new javax.swing.JPanel();
        recipeLabel = new javax.swing.JLabel();
        trendPanel = new javax.swing.JPanel();
        trendLabel = new javax.swing.JLabel();
        campaignPanel = new javax.swing.JPanel();
        campaignLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        welcomePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        welcomePanel.setPreferredSize(new java.awt.Dimension(50, 50));

        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Välkommen [namn]");
        welcomeLabel.setToolTipText("");

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        add(welcomePanel, java.awt.BorderLayout.PAGE_START);

        navigationPanel.setLayout(new javax.swing.BoxLayout(navigationPanel, javax.swing.BoxLayout.LINE_AXIS));

        newsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newsPanel.setPreferredSize(new java.awt.Dimension(105, 301));
        newsPanel.setLayout(new java.awt.GridLayout(0, 1));

        recipeLabel.setText("Dagens recept");

        javax.swing.GroupLayout recipePanelLayout = new javax.swing.GroupLayout(recipePanel);
        recipePanel.setLayout(recipePanelLayout);
        recipePanelLayout.setHorizontalGroup(
            recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recipeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        recipePanelLayout.setVerticalGroup(
            recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recipeLabel)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        newsPanel.add(recipePanel);

        trendLabel.setText("Mattrender");

        javax.swing.GroupLayout trendPanelLayout = new javax.swing.GroupLayout(trendPanel);
        trendPanel.setLayout(trendPanelLayout);
        trendPanelLayout.setHorizontalGroup(
            trendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trendPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trendLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trendPanelLayout.setVerticalGroup(
            trendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trendPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trendLabel)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        newsPanel.add(trendPanel);

        navigationPanel.add(newsPanel);

        campaignPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campaignLabel.setText("Kampanjer");

        javax.swing.GroupLayout campaignPanelLayout = new javax.swing.GroupLayout(campaignPanel);
        campaignPanel.setLayout(campaignPanelLayout);
        campaignPanelLayout.setHorizontalGroup(
            campaignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campaignPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campaignLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        campaignPanelLayout.setVerticalGroup(
            campaignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campaignPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campaignLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        navigationPanel.add(campaignPanel);

        add(navigationPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campaignLabel;
    private javax.swing.JPanel campaignPanel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JPanel newsPanel;
    private javax.swing.JLabel recipeLabel;
    private javax.swing.JPanel recipePanel;
    private javax.swing.JLabel trendLabel;
    private javax.swing.JPanel trendPanel;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
