/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat;

import java.awt.GridLayout;
import java.util.ArrayList;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ProductCategory;

/**
 *
 * @author kakan
 */
public class WelcomePanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer welcomePanel
     */
    public WelcomePanel() {
        initComponents();
        
        ProductCategoryPanel campaignProducts = new ProductCategoryPanel(ProductCategory.POD);
        
        campaignProducts.remove(campaignProducts.filterPanel);
        
        contentPanel.add(campaignProducts);
        
        welcomeLabel.setText("Välkommen " + IMatDataHandler.getInstance().getCustomer().getFirstName());
       
        this.revalidate();
        this.repaint();
        
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newsPanel = new javax.swing.JPanel();
        recipeOfTheDaySubtitle = new javax.swing.JLabel();
        recipeOfTheDayTitle = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        trendsSubtitle = new javax.swing.JLabel();
        trendsTitle = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextArea();
        contentPanel = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        campaignLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(100, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        newsPanel.setBackground(new java.awt.Color(255, 255, 255));
        newsPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(200, 200, 200)), javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)));
        newsPanel.setAlignmentX(0.5F);
        newsPanel.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        newsPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        newsPanel.setPreferredSize(new java.awt.Dimension(250, 230));
        newsPanel.setLayout(new javax.swing.BoxLayout(newsPanel, javax.swing.BoxLayout.Y_AXIS));

        recipeOfTheDaySubtitle.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        recipeOfTheDaySubtitle.setForeground(new java.awt.Color(200, 200, 200));
        recipeOfTheDaySubtitle.setText("DAGENS RECEPT");
        newsPanel.add(recipeOfTheDaySubtitle);

        recipeOfTheDayTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        recipeOfTheDayTitle.setText("Ninjabiffar med ris");
        recipeOfTheDayTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 20, 0));
        newsPanel.add(recipeOfTheDayTitle);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Nam venenatis nisl at sem blandit, at laoreet sapien auctor. Fusce hendrerit leo sit amet suscipit vestibulum. Integer sem nulla, sollicitudin at nunc sit amet, commodo imperdiet nunc. Aliquam congue ligula eget urna interdum, sit amet lacinia ipsum suscipit. Cras vitae aliquam ante, quis dictum metus. Morbi auctor rhoncus sodales. Etiam malesuada velit ac ligula dapibus, ornare porttitor velit consectetur.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTextArea1.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        newsPanel.add(jTextArea1);

        trendsSubtitle.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        trendsSubtitle.setForeground(new java.awt.Color(200, 200, 200));
        trendsSubtitle.setText("MATTRENDER");
        newsPanel.add(trendsSubtitle);

        trendsTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        trendsTitle.setText("Både gott och nyttigt");
        trendsTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 20, 0));
        newsPanel.add(trendsTitle);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Nam venenatis nisl at sem blandit, at laoreet sapien auctor. Fusce hendrerit leo sit amet suscipit vestibulum. Integer sem nulla, sollicitudin at nunc sit amet, commodo imperdiet nunc. Aliquam congue ligula eget urna interdum, sit amet lacinia ipsum suscipit. ");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setMinimumSize(new java.awt.Dimension(0, 0));
        jTextArea3.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        newsPanel.add(jTextArea3);

        add(newsPanel);

        contentPanel.setLayout(new java.awt.BorderLayout());

        welcomePanel.setBackground(new java.awt.Color(255, 255, 255));
        welcomePanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(200, 200, 200)), javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)));
        welcomePanel.setLayout(new java.awt.BorderLayout());

        welcomeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        welcomeLabel.setText("Välkommen Alexandra");
        welcomeLabel.setToolTipText("");
        welcomeLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        welcomePanel.add(welcomeLabel, java.awt.BorderLayout.PAGE_START);

        campaignLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        campaignLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        campaignLabel.setText("Just nu har vi 42 varor på kampanj.");
        campaignLabel.setToolTipText("");
        welcomePanel.add(campaignLabel, java.awt.BorderLayout.CENTER);

        contentPanel.add(welcomePanel, java.awt.BorderLayout.PAGE_START);

        add(contentPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campaignLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel newsPanel;
    private javax.swing.JLabel recipeOfTheDaySubtitle;
    private javax.swing.JLabel recipeOfTheDayTitle;
    private javax.swing.JLabel trendsSubtitle;
    private javax.swing.JLabel trendsTitle;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
